name: fresh_notes
description: A cross-platform, open-source notes app.
publish_to: 'none'
version: 1.0.0+1
repository: https://github.com/freshtechtips/fresh-notes-app
platforms:
  android:
  ios:
  # linux:
  macos:
  # web:
  # windows:

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Firebase packages && plugins
  firebase_core: ^2.21.0
  firebase_app_check: ^0.2.1+3
  firebase_auth: ^4.12.1
  cloud_firestore: ^4.12.2
  firebase_storage: ^11.4.1
  firebase_crashlytics: ^3.4.3
  firebase_analytics: ^10.6.3

  # Core plugins
  path_provider: ^2.1.1
  sqflite: ^2.3.0

  # Other plugins
  image_picker: ^1.0.4
  image_picker_android: ^0.8.8+2
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^5.0.0
  share_plus: ^7.2.1
  connectivity_plus: ^5.0.1

  # Core packages
  path: ^1.8.3
  logging: ^1.2.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.2
  intl: ^0.18.1
  meta: ^1.9.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  # go_router: ^11.1.2
  # flutter_platform_widgets: ^4.0.0-beta.3

  flutter_quill: ^8.2.5
  flutter_quill_extensions: ^0.6.3

  # Other packages
  flutter_dotenv: ^5.1.0
  lottie: ^2.7.0
  cached_network_image: ^3.3.0

  # Other ui packages
  bot_toast: ^4.1.3

# Replace the path with your local packages if you working on them, otherwise please comment the dependency_overrides section
# dependency_overrides:

#   flutter_quill:
#     path: ../flutter-quill
#   flutter_quill_extensions:
#     path: ../flutter-quill/flutter_quill_extensions
#   flutter_quill_test:
#     path: ../flutter-quill/flutter_quill_test

dev_dependencies:
  test: ^1.24.3
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  flutter_quill_test: ^0.0.4

flutter:

  generate: true
  uses-material-design: true

  assets:
    - .env
    - ./assets/