name: fresh_notes
description: A cross-platform, open-source notes app.
publish_to: 'none'
version: 1.0.0+1
repository: https://github.com/freshtechtips/fresh-notes-app
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  # Flutter packages
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Firebase packages && plugins
  firebase_core: ^2.24.0
  firebase_app_check: ^0.2.1+6
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.3
  firebase_storage: ^11.5.3
  firebase_crashlytics: ^3.4.6
  firebase_analytics: ^10.7.2

  # Core plugins
  path_provider: ^2.1.1
  sqflite: ^2.3.0

  # Other plugins
  image_picker: ^1.0.4
  image_picker_android: ^0.8.8+2
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^5.0.0
  share_plus: ^7.2.1
  connectivity_plus: ^5.0.2

  # Core packages
  path: ^1.8.3
  logging: ^1.2.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.2
  intl: ^0.18.1
  meta: ^1.10.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  # go_router: ^11.1.2
  # flutter_platform_widgets: ^4.0.0-beta.3

  fresh_base_package:
    git: 
        url: https://github.com/freshtechtips/flutter-fresh-base-package.git
        ref: main

  flutter_quill: ^8.6.3
  flutter_quill_extensions: ^0.7.2

  # Other packages
  lottie: ^2.7.0
  cached_network_image: ^3.3.0

  # Other ui packages
  

dev_dependencies:
  test: ^1.24.9
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  flutter_gen_runner: ^5.3.2
  flutter_quill_test: ^0.0.5

flutter:

  generate: true
  uses-material-design: true

  assets:
    - .env
    - ./assets/images/
    - ./assets/json/

flutter_gen:

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true