name: fresh_notes
description: A cross-platform, open-source notes app.
publish_to: 'none'
version: 0.0.1+1
repository: https://github.com/freshplatform/fresh-notes
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  # Flutter packages
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Firebase packages && plugins
  firebase_core: ^2.24.0
  firebase_app_check: ^0.2.1+6
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.3
  firebase_storage: ^11.5.3
  firebase_crashlytics: ^3.4.6
  firebase_analytics: ^10.7.2

  # Core plugins
  path_provider: ^2.1.1
  sqflite: ^2.3.0

  # Other plugins
  image_picker: ^1.0.4
  image_picker_android: ^0.8.8+2
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^5.0.0
  share_plus: ^7.2.1
  connectivity_plus: ^5.0.2

  # Core packages
  path: ^1.8.3
  logging: ^1.2.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.2
  intl: ^0.18.1
  meta: ^1.10.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  # go_router: ^11.1.2
  # flutter_platform_widgets: ^4.0.0-beta.3

  fresh_base_package:
    git:
        url: https://github.com/freshplatform/flutter-fresh-base-package.git
        ref: main

  flutter_quill: ^8.6.4
  flutter_quill_extensions: ^0.7.2

  # Other packages
  lottie: ^2.7.0
  cached_network_image: ^3.3.0

  # Other ui packages
  smooth_page_indicator: ^1.1.0
  flutter_staggered_grid_view: ^0.7.0
  

dev_dependencies:
  test: ^1.24.9
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  flutter_gen_runner: ^5.3.2
  flutter_quill_test: ^0.0.5

  auto_screenshot: ^0.0.2
  icons_launcher: ^2.1.5

dependency_overrides:
  flutter_inappwebview: ^6.0.0-beta.30
  flutter_keyboard_visibility:
    git: https://github.com/MisterJimson/flutter_keyboard_visibility.git

flutter:

  # generate: true
  uses-material-design: true

  assets:
    - .env
    - ./assets/images/
    - ./assets/json/
    - ./assets/lottie/onboarding/

flutter_gen:

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true


icons_launcher:
  image_path: "assets/images/app_logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    macos:
      enable: true
    windows:
      enable: true
    linux:
      enable: true
    web:
      enable: true

auto_screenshot:
  bundle_id: 
    android: net.freshplatform.fresh_notes
    ios: net.freshplatform.freshNotes
  devices:
    - iPhone 8 Plus
    - iPhone 13 Pro Max
    - iPad Pro (12.9-inch) (2nd generation)
    - iPad Pro (12.9-inch) (5th generation)
    - Pixel_3a_API_33_arm64-v8a
    - Pixel_5_API_33
  base_url:
    android: https://notes.freshplatform.net/
    ios: https://notes.freshplatform.net/
  screenshot:
    - /
    - /about
    - /settings