name: fresh_notes
description: A cross-platform, open-source notes app.
publish_to: 'none'
version: 0.0.2-dev.2+18
repository: https://github.com/FreshKernel/fresh-notes
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  # Flutter packages
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase packages && plugins
  firebase_core: ^3.6.0
  firebase_app_check: ^0.3.1
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3

  # Core plugins
  path_provider: ^2.1.4
  sqflite: ^2.3.3

  # Other plugins
  image_picker: ^1.1.2
  image_picker_platform_interface: ^2.10.0
  image_picker_android: ^0.8.9+1
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.2
  url_launcher: ^6.3.0
  gal: ^2.3.0
  uuid: ^4.2.1
  cross_file: ^0.3.4
  # home_widget: ^0.4.1
  printing: ^5.13.3

  # Core packages
  path: ^1.8.3
  logging: ^1.2.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5
  intl: ^0.19.0
  meta: ^1.10.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  go_router: ^14.2.8
  http: ^1.2.2

  fresh_base_package:
    git:
        url: https://github.com/freshplatform/flutter-fresh-base-package.git
        ref: main

  flutter_quill: ^11.0.0-dev.1
  flutter_quill_extensions: ^11.0.0-dev.1
  flutter_quill_to_pdf: ^2.2.5

  # Other packages
  lottie: ^3.1.2
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.9
  flutter_dotenv: ^5.1.0
  mime: ^1.0.4
  pdf: ^3.10.7
  screenshot: ^3.0.0

  # Other ui packages
  smooth_page_indicator: ^1.1.0
  flutter_staggered_grid_view: ^0.7.0
  auto_size_text: ^3.0.0

dependency_overrides:
  # TODO: To fix related build failure
  win32: ^5.5.4

dev_dependencies:
  test: ^1.24.9
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  flutter_gen_runner: ^5.3.2
  flutter_quill_test: ^11.0.0-dev.1
  bloc_test: ^9.1.5

  yaml: ^3.1.2
  icons_launcher: ^3.0.0

flutter:

  generate: true
  uses-material-design: true

  assets:
    - .env
    - ./assets/images/
    - ./assets/svg/
    - ./assets/lottie/onboarding/
    - ./assets/lottie/page_not_found/
    - ./assets/lottie/error/
    - ./assets/lottie/no_data/
    - ./assets/lottie/no_internet/
    - ./assets/lottie/auth/
    - shorebird.yaml

flutter_gen:

  integrations:
    flutter_svg: true
    lottie: true


icons_launcher:
  image_path: "doc/assets/app_logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    macos:
      enable: true
    windows:
      enable: true
    linux:
      enable: true
    web:
      enable: true
