name: Build the app

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_linux:
    name: Build Linux and Web Apps
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Check flutter version
        run: flutter --version

      - name: Fallbacks
        run: ./scirpts/fallback.sh
    
      - name: Install dependencies
        run: flutter pub get
      
      - name: Flutter build Web
        run: flutter build web --release --verbose --dart-define=CI=true

      - name: Install flutter Linux prerequisites
        run: sudo apt-get install clang cmake git ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev -y

      - name: Flutter build Linux
        run: flutter build linux --release --verbose --dart-define=CI=true

  build_windows:
    name: Build Windows App
    runs-on: windows-latest

    steps:
        - uses: actions/checkout@v4
        - uses: subosito/flutter-action@v2
          with:
            channel: 'stable'
            cache: true
  
        - name: Check flutter version
          run: flutter --version
  
        - name: Fallbacks
          run: ./scirpts/fallback.sh
        
        - name: Install dependencies
          run: flutter pub get
        
        - name: Flutter build windows
          run: flutter build windows --release --verbose --dart-define=CI=true

  build_macOS:
    name: Build macOS App
    runs-on: macos-latest

    steps:
        - uses: actions/checkout@v4
        - uses: subosito/flutter-action@v2
          with:
            channel: 'stable'
            cache: true
  
        - name: Check flutter version
          run: flutter --version
  
        - name: Fallbacks
          run: ./scirpts/fallback.sh
        
        - name: Install dependencies
          run: flutter pub get
        
        - name: Flutter build macOS
          run: flutter build macos --release --verbose --dart-define=CI=true
        - name: Flutter build iOS
          run: flutter build ios --release --verbose --dart-define=CI=true
    
  