name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Check flutter version
        run: flutter --version

      - name: Create empty .env file
        run: touch .env

      - name: Create generated firebase_options.dart
        run: mv lib/firebase_options.fallback.dart lib/firebase_options.dart

      - name: Install dependencies
        run: flutter pub get

      - name: Run flutter analysis
        run: flutter analyze

      - name: Check dart code formatting
        run: dart format --set-exit-if-changed .
      
      - name: Preview dart proposed changes
        run: dart fix --dry-run

      - name: Run flutter tests
        run: flutter test
      
      - name: Flutter build Web
        run: flutter build web --release --verbose --dart-define=CI=true

      - name: Install flutter Linux prerequisites
        run: sudo apt-get install clang cmake git ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev -y

      - name: Flutter build Linux
        run: flutter build linux --release --verbose --dart-define=CI=true
