name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Check flutter version
        run: flutter --version

      - name: Fallbacks
        run: ./scirpts/fallback.sh

      - name: Install dependencies
        run: flutter pub get

      - name: Run flutter analysis
        run: flutter analyze

      - name: Check dart code formatting
        run: dart format --set-exit-if-changed .
      
      - name: Preview dart proposed changes
        run: dart fix --dry-run

      - name: Run flutter tests
        run: flutter test
